#!/bin/bash
#SBATCH --mem=100000M
#SBATCH --time=16:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=16
#SBATCH --mail-user=<russell.jasper@unibe.ch>
#SBATCH --mail-type=FAIL,END
#SBATCH --output=slurm-%x.%j.out
module load vital-it/7
module load SequenceAnalysis/GenePrediction/prodigal/2.6.3
module load SequenceAnalysis/HMM-Profile/hmmer/3.1b2
module load UHTS/Analysis/pplacer/1.1.alpha19
module load Python/3.10.8-GCCcore-12.2.0
checkm2 predict --input 01_input_bins --output 02_CheckM2 --force -x fa -t 16
