#!/bin/bash
#SBATCH --mem=4000M
#SBATCH --time=6:00:00
#SBATCH --mail-user=<russell.jasper@unibe.ch>
#SBATCH --mail-type=END,FAIL
#SBATCH --output=slurm-%x.%j.out
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --partition=pibu_el8 

module load prodigal/2.6.3-GCCcore-10.3.0

INDIR=/data/projects/p898_Deer_RAS_metagenomics/04_Deer/03_assembly
OUTDIR=/data/projects/p898_Deer_RAS_metagenomics/04_Deer/03b_Prodigal_on_assemblies


cd $INDIR

for i in *filtered.contigs.fasta
do
 sample=
 prodigal -i $i -o "$OUTDIR"/Genes/"$i".genes -a "$OUTDIR"/FAA/"$i".genes.faa -d "$OUTDIR"/FNA/"$i".genes.fna -m -p single
done
