#!/bin/bash
#SBATCH --mem=200000M
#SBATCH --time=96:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --mail-user=<russell.jasper@unibe.ch>
#SBATCH --mail-type=FAIL,END
#SBATCH --output=slurm-%x.%j.out
#SBATCH --partition=pibu_el8   
dRep dereplicate 03_drep_bins \
-g 01_input_bins/*fa \
-comp 70 -con 10 \
--S_algorithm ANImf \
--gen_warnings -ms 10000 -pa 0.8 -sa 0.95 -nc 0.30 \
--genomeInfo genomeInformation_ALL.csv \
-p 24 \
-comW 1 -conW 5 -N50W 6 -sizeW 0.5 ## add heavy N50 weight, and minor genome size weight (default complete/contam)
